kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
  namespace: prometheus
  annotations:
    prometheus.io/port: '9090'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
  selector:
    app: prometheus-server
  type: ClusterIP
  sessionAffinity: None