apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5zbWFydGZvcmNlLmVzLmFpcmJ1c2RzLmNvcnAiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiUmVhbG1hZHJpZDg4ISIsImF1dGgiOiJZV1J0YVc0NlVtVmhiRzFoWkhKcFpEZzRJUT09In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: prometheus
type: kubernetes.io/dockerconfigjson